### ISSUE TITLE
Investigate calculation errors

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#10]
In the test account, there is a "small funder" grant.  It has several activities filled in (though not all).  The total cost of those activities should be $346, but the results reflect $0 (and the net grant value is therefore also incorrect).

The "big name funder" grant costs are also incorrect, though only slightly off.  The grant cost should be $1500, but is $1,643.84 in the grant calc.

**Comment by readywater** [comment]
I think I tracked down one of the bugs. (Small grant being 0 cost)
There's not a smart default set on the selection, so it looks like you're assigning it to the boss, but actually you're assigning it to no one. Will look for a solve on this and go from there.

**Comment by readywater** [comment]
Just following up on this one.
There's a debug mode at the bottom of the screen, so you can see where the NULL exists, that just gets interpreted as a multiply-by-0 in that part of the calculation. Pretty sure this is the solve, but next step will be to reset the DB and recreate with the new experience.
Additionally, when multiples are added (still researching how to do that without breaking a lot of things), I'll add in additional validation protection.

<img width="485" alt="screen shot 2018-02-05 at 9 26 48 am" src="https://user-images.githubusercontent.com/202041/35809412-8c10814c-0a56-11e8-9e58-ad17e4b2a4a9.png">

**Comment by dahnag** [comment]
Thanks.  Happy to retest whenever that would be helpful.

**Comment by dahnag** [comment]
@readywater has this been resolved?

**Comment by dahnag** [comment]
@readywater has this been resolved?

**Comment by dahnag** [comment]
@readywater has this been resolved?
