### ISSUE TITLE
Grantmaker - results page - update text

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#100]
* Cost to administer program - grantmaker
* It’s not clear what to do with these numbers (so need to make it clear)
* What does this all mean (each number)? How was it derived (not the details of the math, necessarily) – maybe include a link to how we did the math (look for blog post re net grant)

Add link to this post: How did we do the math? https://www.peakgrantmaking.org/blog/net-grants-how-much-is-that-grant-really-worth/

**Comment by readywater** [comment]
1097b0b
