### ISSUE TITLE
Grantseeker - grant program page - text updates

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#101]
Add instructional text at top: If you’ve visited this tool before and saved your template, you may pre-load your data to start from in order to analyze a different potential grant. Note: Any changes you have already made will not be changed by the template.

If this is your first time using this tool, you will not have any templates below to choose from.

Grant Information, Details, and Logistics
Fill in the information below about a specific grant, details, and logistics, . We will use this to calculate the final net grant. You may choose whether to save your own work as a template to work from for additional grants you may analyze using this tool.

**Comment by dahnag** [comment]
@readywater Like with #98, I need a pointer to where this should be updated.

**Comment by readywater** [comment]
75fef8c
