### ISSUE TITLE
Provide feedback mechanism

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#16]
Each page in the grant calc (for both grantseeker and grantmaker) should have a mechanism for providing feedback (for example, a floating "feedback" button that enables users to click the button and fill out a form or send an email to provide feedback).

**Comment by readywater** [comment]
Thinking of using this.
https://usabilla.com

**Comment by dahnag** [comment]
Looks good.  Is there an associated cost?

**Comment by readywater** [comment]
Link to feedback form
https://goo.gl/forms/qkGEc8joAGwtzgt53
