### ISSUE TITLE
Draft additional text/other content for results pages

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#17]
In addition to the calculated results, the results pages should provide additional information to make the calculations actionable.

**Comment by readywater** [comment]
https://docs.google.com/document/d/15FHFDJYyaEz0JGJ5lY-Z6T3NmwQPtBq-xqQKN5-a7-o/edit?usp=sharing

Draft text for results pages for grant calc

Grantseeker

How to use this information:
The purpose of this tool is to help you and your organization decide which grants to pursue - and which grants not to pursue.  While there is no bright line test for when a grant is not worth pursuing, think about whether the net grant value for this grant is sufficient for your organization to do what it needs to do with those grant funds.  Will it cover the expenses your organization needs it to cover?  If some - or all - of the grant is restricted, will it still cover the expenses your organization needs it to cover?

Deciding whether or not to pursue a grant is not only a matter of looking at each individual grant opportunity; it’s also a matter of looking at each opportunity relative to other opportunities.  Take into account both the net value of each grant opportunity and the amount of effort that is required for each opportunity.  Keep in mind that each grant your organization pursues has an associated opportunity cost; the hours spent pursuing one grant cannot be spent pursuing a different grant.  Sometimes a large grant with a low probability of award and a high level of effort is not a good investment of time relative to a smaller grant with a higher probability that requires less effort.

(toying with an additional calculation - something like return on effort -

Return on Effort = (Net Grant Value / Total Cost of Time Spent) * 100

We can then use this as a comparative tool - makes things a bit more absolute)



Grantmaker

We can link to PEAK resources here.  I’ll ask them again for any text they might want to have on this screen.

**Comment by dahnag** [comment]
@readywater if you can give me a pointer on how to add to the results pages, I'm happy to do it.

**Comment by dahnag** [comment]
@readywater is there a file where I can drop content in for the results pages?
