### ISSUE TITLE
Add a new step for filling in profile on /list page

### ISSUE THREAD

**Issue by readywater** [Mulligan-Fund/grant-calculator#19]
- [x] Create new page for adding lists.
- [x] Set up Org Info yml file and table setup using forms page
- [x] Fields for individual: First name, last name, Title (note: original issue had suggested including email, but we've already captured email)
- [x] Fields for org: EIN, Name, State, Operating Budget, Number of employees, Grants received annually, Amount in grant funding received annually

**Comment by readywater** [comment]
@dahnag, if you could fill in the fields in this file:
https://github.com/Mulligan-Fund/grant-calculator/blob/master/_data/orginfo.yml

**Comment by readywater** [comment]
Hey Dahna, this section is fully up and working (fixed a big bug thismorning). Only thing left is to fill in all the information.

**Comment by dahnag** [comment]
@readywater added fields.
