### ISSUE TITLE
Create About Page Copy

### ISSUE THREAD

**Issue by readywater** [Mulligan-Fund/grant-calculator#20]
About Grant Calc
 -> Link to Article on PEAK
About Organizations
 -> Link to each
About Mulligan

**Comment by dahnag** [comment]
_About the Net Grant Calculator_
The Net Grant Calculator helps both not-for-profits and grantmakers evaluate the net value a grant will provide. For not-for-profits, the calculator provides a tool to help decide which grants to pursue. For grantmakers, the calculator helps understand the impact on grantees of application and management processes and helps identify ways to increase their grants' net value to grantees. It also helps grantmakers understand the cost of running a grant program to help identify ways to streamline internal processes.

We built the Net Grant Calculator to help organizations maximize their net grant values to help ensure as much net grant money as possible goes to program and service delivery.

Read more [here](https://www.peakgrantmaking.org/blog/net-grants-how-much-is-that-grant-really-worth/).

_How to Use the Net Grant Calculator_
To get the most value from this tool, you’ll need information about who in your organization is involved with different stages of the grant process and how much time they spent. If you don’t know exact numbers, you can use estimates and still get a good sense of the net value of a particular grant or program.
 
It will also help to have an idea of the salaries of people involved in the grant process. Don’t worry; we understand that salaries are sensitive information, and the tool doesn’t ask for names. But understanding how much time staff members are spending and the cost of that time is a key component in assessing net grant values. If you don’t know or don’t want to input that information, you can use industry averages, which the tool will help you fill in based on job title.

_The Organizations Behind the Net Grant Calculator_

(Peak Logo)
[PEAK Grantmaking](https://www.peakgrantmaking.org) is a member-led national association of professionals who specialize in grants management for funding organizations. The people of PEAK Grantmaking come together to form a vibrant community of grantmaking practice that advances shared leadership and learning across the sector.

This is where Practice Meets Purpose. By cultivating resources, learning opportunities, and collaborations across the philanthropic spectrum, we support grantmaking practices designed to maximize mission-driven efficiency and effectiveness of funders of every size.

(NA Logo)
[New America](https://www.newamerica.org): Founded in 1999, New America is a think tank and civic enterprise committed to renewing American politics, prosperity, and purpose in the Digital Age. We generate big ideas, bridge the gap between technology and policy, and curate broad public conversation. 

(Mulligan Fund Logo)
The Mulligan Fund is dedicated to helping create stronger and more effective organizations in the not-for-profit sector.  Through tools, research, pooled funding, and capacity-building technical assistance, Mulligan Fund leverages capital - philanthropic, intellectual, and human - to support and scale world-changing ideas and organizations.

**Comment by readywater** [comment]
1737230

**Comment by readywater** [comment]
d500e84
