### ISSUE TITLE
Add "delete" function for grants/programs

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#21]
If a user adds a grant or a program in error, they should be able to delete the grant/program.

We need to define the conditions under which deletion is possible.  If no data has been entered in the grant or program, it can be deleted.  If some data has been entered, deleting the grant/program could require an extra step, or the user could be given a message indicating that they need to delete all data from the grant/program before deleting it.

**Comment by readywater** [comment]
Resolved on Server side by commit: b779475
