### ISSUE TITLE
Fully implement registration

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#24]
New users can create accounts
Home page has both registration functionality and login functionality for existing users

**Comment by dahnag** [comment]
@readywater we need a method for password recovery.

**Comment by readywater** [comment]
https://www.npmjs.com/package/password-reset

**Comment by readywater** [comment]
Commit 56ce90a in grant-calculator-server covers the basics of the API.
Still need to:
- Implement frontend
- Implement email solution

**Comment by dahnag** [comment]
This was closed months ago.
