### ISSUE TITLE
Add hint text to team page

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#29]
- [x] Draft hint/guidance/tool tip text to be provided on team page - Dahna
- [ ] Implement hint/guidance/tool tip text to be provided on team page - Andrew

**Comment by dahnag** [comment]
Text for team page:
Please add any staff members that are involved in each activity in the grant process - from initial research to close-out - and how much time (in hours) is spent by each person on each activity. Include a name (for easy selection) and a role (choose from CEO, Other C-Suite, Financial Staff, Director of Development, Development Staff, Administrative Staff, Program Officer, Grant Manager, Technology Staff, Data Analyst, etc.)

You may add an annual salary amount or, if you don’t know this information or do not want to share it, you can use the pre-calculated amounts populated by generally accepted salary surveys.

**Comment by readywater** [comment]
Resolved by 290b63a
