### ISSUE TITLE
Add "top 10 ways to improve" practices text for grantmaker results page

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#30]
- [x] PEAK to provide text for "top 10 ways to improve" practices for grantmaker results page
- [x] Dahna to coordinate
- [x] Dahna to implement text on grantmaker results page

**Comment by dahnag** [comment]
This has been completed.

**Comment by MelissaSines** [comment]
*****
https://netgrant.org/result?id=5c547aa5c41dd7000482402e

Grant result page has the wrong text it currently has the grantseeker text.

Update this text to:

Grantmaking achieves its broadest impact when true partnerships unite grantmakers and grantseekers in service to the greater good. Based on trust and respect, these partnerships ascribe equal value to the experiences, resources, and needs of each partner.

Grantmakers that respect the grantee experience rightsize the grantmaking process for the type, size, and/or previous relationships with grantees and implement flexible practices that consider that not all grantseekers bring the same resources to the process.

Grants management professionals are at the nexus of their organizations and those seeking grants. They can implement practices and policies that build trust, redefine the power balance, and narrow the power gap.

Board members and senior leaders at grantmaking organizations should commit to intentionally building power and capacity within nonprofit partners and to ceding space for solutions that come from grantseekers and grantees.

PEAK Grantmaking calls on grantmakers to adopt policies and practices that shift grantmaking to a more balanced partnership for social change and give up some of their power.

Read more about Narrowing the Power Gap (Link - Open in new page) here.

https://www.peakgrantmaking.org/improve-your-grantmaking/implement-better-practices/narrow-the-power-gap/

**Comment by dahnag** [comment]
@melissaSines it seems like there was one button that was linked to the wrong results page.  I think we've fixed it.  Can you try and see if you're still experiencing the same issue?

If it's pointing to the right page now, you should see the text PEAK had previously provided with tips for grantmakers.  Do you want to keep the existing text, or replace it with the new text in this issue?
