### ISSUE TITLE
Connect to netgrant.org

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#31]
- [ ] Dahna to coordinate credentials
- [ ] Andrew to implement

**Comment by readywater** [comment]
Heyo, who has control over this right now? Getting this connected is pretty simple.
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by dahnag** [comment]
Note: for the time being, netgrant.org is redirecting to the MailChimp signup form, which will work for managing early feedback.  Moving this issue to version 2.

**Comment by readywater** [comment]
We're set up to have it pointed see: 82f2b63
