### ISSUE TITLE
Use grantseeker data to provide estimates for time required by grantees for the grantmaker calculation

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#32]
After the calculator has collected a critical mass of user data, we will develop an approach to using average numbers to automatically populate the time required and related costs from the grantseeker perspective to populate the grantmaker calculation for the net value to the grantee (i.e., the part of the tool that currently requires the grantmaker to either know or estimate how long grantees/grantseekers spend on different parts of the process).

**Comment by dahnag** [comment]
There are two related needs here:
- grantmakers do not have a good sense of how long it takes grantees to do things (part of what we're trying to help address)
- grantees/applicants feel daunted looking at the tool re: amount of information they need to enter

Both of these issues can be addressed with a single solution: creating some "standard" grants that can pre-populate data for both grantseekers and grantmakers.  The pre-filled data can then be edited (both for more accurate results and for better data collection and analysis).

Current planned approach:
- PEAK will develop "standard" grants by size (3 buckets), support time (gen op vs program or other more specific), and relationship (new grantee/return grantee)
- Andrew/Dahna will implement a mechanism for users to start from one of the "standard" grants, while providing an easy ability to update individual data fields
  - for grantseeker, when creating a new grant, select start from template or start from scratch
  - (need to find right place in workflow for grantmaker)
  - tool will ask a series of questions re: size, support type, relationship
  - results page will select template to use
  - user then completes the information for the given grant, using either the values from the standard grant or by replacing those values where appropriate

**Comment by MelissaSines** [comment]
Size of Grant
50K or less
50K – 250K
250K+

Type of Grant
Project or Program Support (Restricted)
Operating or General Support (Unrestricted)

Relationship
First-time Grantee
Previous Grantee
