### ISSUE TITLE
Add link for users to access/download user guide

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#38]

**Comment by readywater** [comment]
Hey @dahnag, can you link to the content and/or upload the guide here so I can stick it up?

**Comment by dahnag** [comment]
We don't have final copy yet. I'll upload it here when we do.

**Comment by dahnag** [comment]
We discussed adding the current version of the doc, but it has a bunch of tracked changes, etc.  Let's wait until we have a final (or near-final) version.

**Comment by dahnag** [comment]
[Net Grant Calculator User Guide.pdf](https://github.com/Mulligan-Fund/grant-calculator/files/1880671/Net.Grant.Calculator.User.Guide.pdf)
Here's the user guide.
