### ISSUE TITLE
Team page - "save" button doesn't work in Chrome on PC

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#45]
On https://mulligan-fund.github.io/grant-calculator//people, the "save" button does not work in Chrome on a PC.  Could be related to login issue (#42)

**Comment by readywater** [comment]
Unfortunately I have no way of recreating this issue. No access to a PC.

**Comment by dahnag** [comment]
How about something like https://screenster.io?

**Comment by dahnag** [comment]
This is a visual feedback issue, not a Chrome/PC issue.  See #44 (and #43)
