### ISSUE TITLE
no clear way to leave profile page

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#47]
When I went to select whether my org was a grantmaker or grantseeker, there was no clear way to leave that page.  There needs to be a "save" button, or a "save and return to dashboard" - some way for the user to indicate that they have completed that page and are moving on.

![image](https://user-images.githubusercontent.com/32071209/38436059-9bb8b036-39a1-11e8-9b47-15450967765d.png)

**Comment by readywater** [comment]
Resolved with 0355ef4
