### ISSUE TITLE
add marketing assets to repo

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#52]
Logos, other graphics, relevant language.  
Specific requests:
Logos:

- [x] Grant Calc 
- [x] NA 
- [x] Mulligan
Mission 2-liners:
- [x] NA
- [x] Mulligan

**Comment by MelissaSines** [comment]
Melissa will also add the draft marketing language and other images shared on our call. Is the repository created yet?

**Comment by dahnag** [comment]
@MelissaSines you can upload files/images here: https://github.com/Mulligan-Fund/grant-calc-marketing/upload/master

**Comment by MelissaSines** [comment]
At that link I get this message
![image](https://user-images.githubusercontent.com/36712726/41418745-5f4fd874-6fbe-11e8-936e-360ec246b7cf.png)

**Comment by dahnag** [comment]
@readywater , can you troubleshoot so that Melissa can upload?

**Comment by readywater** [comment]
@MelissaSines Try now, I've upgraded your permissions in the repo.

**Comment by MelissaSines** [comment]
Done! Still to come: Andrew will add video he made for New America, write up a potential tech-focused blog on open source software in the nonprofit sector - why it's important, who is doing it, who benefits, how the net grant calc fits into that environment, etc. Melissa will also be working on an explainer video once we are further along with v2.
