### ISSUE TITLE
Instructional text on first page

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#58]
Seems from the feedback that it might be helpful to have a bit of instructional text (in addition to the user guide) right when users log in.
Let's discuss what's needed ("download the user guide to get started?" Or more specific instructions for first steps)
@melissasines - what your take on this?

**Comment by dahnag** [comment]
For one specific bit of feedback:
![image](https://user-images.githubusercontent.com/32071209/41859166-92287202-7869-11e8-950e-c01e2f09ff96.png)
We're addressing a couple of confusing things in other issues (messaging re: grant program vs grant in  #53 and the visual of the button text placement in #54), but it does seem like at least a bit of additional instruction would be beneficial.

**Comment by dahnag** [comment]
Additional feedback re: instructions:
![image](https://user-images.githubusercontent.com/32071209/41861439-4c66c2e0-786f-11e8-920e-608785caaa4d.png)

@melissasines : your thoughts?

**Comment by dahnag** [comment]
and: 
![image](https://user-images.githubusercontent.com/32071209/41861452-55197266-786f-11e8-9d7e-630de9b157ec.png)
Perhaps this could be added to the user guide?

**Comment by MelissaSines** [comment]
This tool is essentially a process mapping tool that allows you to enter time devoted to specific grantseeking or grantmaking tasks, the team members involved in the process, and the salary for these team members. This information is then used to calculate the "Net Grant."

The tool is divided into two areas:

•	Apply for a Grant - This section is to be filled out by Grantseekers. Grantseekers will be able to choose a template based on some basic information that will prefill grantseeking information. From there, they can adjust the hours, salary information, and team members to more closely match their internal processes.

•	Create a Grant - This section is to be filled out by Grantmakers. You will be able to use the tool to map your process, estimate the number of hours spent on internal tasks, update salary information, and add additional team members to customize the calculator. 

In addition, grantmakers will be able to choose a template based on some basic information that will pre-fill grantseeking information to help them better understand the typical time and resource commitments for small or large grants, new or renewal grants, and project or operating grants. 

Grantseekers and grantmakers should consider excluding from consideration any grants that don't fit the "usual" process (like board discretionary, employee matching grants, or sponsorships) and focus on grants where there is the most interaction between grantseekers/grantees, and grantmakers.

A detailed User Guide (LINK TO USER GUIDE) is available to help you understand the scope of questions you will be asked.

**Comment by MelissaSines** [comment]
I think this goes on the dashboard page, above where we currently have the download link for the User Guide.
