### ISSUE TITLE
Review whether all currently-requested information in grantmaker profile is necessary

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#64]
Grantmaker feedback suggested they would have preferred to be asked fewer profile questions.  review existing questions to see if there are any that can be reasonably removed (vs. optional questions that can be skipped).

**Comment by MelissaSines** [comment]
Decision- keep these but ensure that it's clear what information is required and what information is optional. We may also want to highlight at the top WHY we are asking for this information and include a link to the privacy policy.

**Potential WHY text:** While most of these fields are not required to create your account, we are requesting that you opt-in to provide the optional information. Your data is secure and we will not share individual grantmaker information. This optional information will help us better understand the differences in processes inside different types of grantmakers.

**Comment by MelissaSines** [comment]
This text should be added to the Grantmaker Profile page at the top

**Comment by dahnag** [comment]
Made this generic to both types of organizations.
