### ISSUE TITLE
Update text on homepage

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#7]
Text on homepage should read:

How much is that grant really worth?  The Net Grant Calculator will help you find out.
 
The Net Grant Calculator helps both not-for-profits and grantmakers evaluate the net value a grant will provide. For not-for-profits, the calculator provides a tool to help decide which grants to pursue. For grantmakers, the calculator helps understand the impact on grantees of application and management processes and helps identify ways to increase their grants' net value to grantees. It also helps grantmakers understand the cost of running a grant program to help identify ways to streamline internal processes.
 
To get the most value from this tool, you’ll need information about who in your organization is involved with different stages of the grant process and how much time they spent. If you don’t know exact numbers, you can use estimates and still get a good sense of the net value of a particular grant or program.
 
It will also help to have an idea of the salaries of people involved in the grant process. Don’t worry; we understand that salaries are sensitive information, and the tool doesn’t ask for names. But understanding how much time staff members are spending and the cost of that time is a key component in assessing net grant values. If you don’t know or don’t want to input that information, you can use industry averages, which the tool will help you fill in based on job title.
 
This tool is a project of PEAK Grantmaking, New America, and the Mulligan Fund.

**Comment by readywater** [comment]
i think the content here is a bit too long by about two paragraphs. Would recommend using this as a template to design a home page more descriptive of the value proposition once the core issues are handled.

In the interim, the changes are reflected in 64a285b

**Comment by dahnag** [comment]
The initial vision/sketch design was that there would be a home page that was distinct from the login page.  In addition to text on the home page, there would be links to:
* sign up/ sign in
* about
* contact

Happy to revisit.  Perhaps this lengthier version can be part of an about page.

**Comment by dahnag** [comment]
Tagline: Get Your Grant's Worth

Grantseeker:
**Decide which grants to pursue**
The net grant calculator helps you decide which grant to pursue, and prioritize those grants with this highest net grant value to your organization

Grantmaker:
**Know the cost of your grants**
How much does it cost to run each of your grant programs?  How much does it cost your grantees to apply?  Find out with the net grant calculator.

_Data-Driven Decisions_
Use data about specific grant opportunities to make informed decisions

_Reflect and Learn_
Evaluate and improve grant practices to increase grant efficiency

_Flexible Analysis_
Analysis that matches your organization's grant management processes

_Secure Data_
Store information about grant opportunities securely in the cloud

**Comment by readywater** [comment]
Updated content bc687b0

**Comment by MelissaSines** [comment]
Hi Dahna,

We have a new comms/marketing person on staff (finally!) and she had some suggestions for the home page and about us page:

-------------------------------
Name references are inconsistent. Always refer to it as Net Grant Calculator and capitalize.

***
https://netgrant.org/
changed tense to 2nd person, suggest flipping order, so our primary audience runs first

What is the "net grant?"
Net Grant = Total Grant Amount MINUS the time and resources expended to seek and implement the grant. This tool will help grantmakers and grantseekers calculate and better understand the true cost to your organizations – and to the sector as whole – of making and seeking grants.

Grantmakers: Know the cost of your grant programs.
You want to ensure that the cost to run each of your programs does not eat away at the benefit it offers, and that you are spending time and money on the right parts of the grantmaking process. The Net Grant Calculator helps you map your grantmaking process and understand how much it costs to run each of your grant programs and the amount of time and resources expended by potential grantees to apply.

Grantseekers: Decide which grants to pursue.
You can use the tool to help you calculate – and understand – your return on investment for grantseeking activities and ensure that you’re spending time on what’s most important. The Net Grant Calculator can help you decide which grants to pursue and help you prioritize those grants with the highest net grant value to your organization.

in register box, area with logos, say Net Grant Calculator

***
https://netgrant.org/about/ 

About the Net Grant Calculator

make this an external link open in new window:
Read more here

this referred to nonprofits, but you never refer to them this way on other pages, so adjusted to match. I think this makes more sense in this context anyway:
The Net Grant Calculator helps both grantmakers and grantseekers evaluate the net value a grant will provide. For grantseekers

update our boilerplate:
PEAK Grantmaking is a vibrant, member-led national association of more than 4,000 professionals who specialize in grants management for funding organizations. Together, we share knowledge and foster collaboration to strengthen practice. We enable philanthropy to achieve its full potential to fuel change for good. We are the only organization dedicated solely to advancing the how of grantmaking—the operations that funders undertake to make grants and assess the impact of those investments. We work at the intersection where Practice Meets Purpose.

**Comment by MelissaSines** [comment]
Also - one additional question. I believe this decision was made before my time, but can you remember why we decided to go monochromatic on the logos? My comms person just asked: "While it looks like intent is keep presentation simple and straightforward, any reason not use full-color logos and color?"

**Comment by MelissaSines** [comment]
A few more questions whose answers pre-date me:

Can we switch the font on the site to Ariel? 

And, are we married to the logo? I can't remember where it came from!

**Comment by MelissaSines** [comment]
![net grant equation](https://user-images.githubusercontent.com/36712726/59612450-1b39d500-90eb-11e9-896d-6d0abc1ceb45.jpg)
![NetGrantCalc logo v1](https://user-images.githubusercontent.com/36712726/59628436-a4163800-910e-11e9-9870-ab2ceba65365.png)

**Comment by dahnag** [comment]
Broke these out into separate issues - makes them easier to track:

- [ ] #104 
- [ ] #105 
- [ ] #106

**Comment by MelissaSines** [comment]
thank you! And thanks for opening the Maintenance milestone!
