### ISSUE TITLE
Add some context around why a net grant calculator is needed

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#71]
Grantmaker user feedback:
![image](https://user-images.githubusercontent.com/32071209/41870313-b74e6a9e-7889-11e8-9b9b-c69b48565a90.png)

There is some already on the login screen, but evaluate whether it can/should be punched up, and whether additional intro text on the dashboard screen would be beneficial to this end.

**Comment by dahnag** [comment]
Visual tweak: size of text on index page: make grantseeker/grantmaker bigger to help users locate themselves on the page

**Comment by dahnag** [comment]
@melissasines will review marketing info to potentially update text

**Comment by MelissaSines** [comment]
What is the "Net Grant?"

Net Grant = Total Grant Amount MINUS the Time and Resources expended to seek and implement the grant. (See attached image draft)
[Net Grant Image.docx](https://github.com/Mulligan-Fund/grant-calculator/files/2515866/Net.Grant.Image.docx)


This tool will help grantmakers and grantseekers better understand the cost to their organization - and to the sector as whole - of making and seeking grants.

**Grantmakers:**  The net grant calculator helps you map your grantmaking process and understand how much it costs to run each of your grant programs and the amount of time and resources expended by potential grantees to apply.

As a grantmaker, you want to ensure that the cost to run each of your programs does not eat away at the benefit it offers and ensure that you are spending time and money on the right parts of the grantmaking process.  

**Grantseekers:** The net grant calculator helps you decide which grants to pursue and helps you prioritize those grants with the highest net grant value to your organization. 

Grantseekers can use the tool to help them calculate – and understand – their return on investment for grantseeking activities and ensure that you’re spending time on what’s most important.

**Comment by dahnag** [comment]
@MelissaSines can you email me the file?  I haven't been able to download it.

**Comment by MelissaSines** [comment]
This is potential text for the front page

**Comment by dahnag** [comment]
![image](https://user-images.githubusercontent.com/32071209/48991660-d5430280-f101-11e8-8df3-09ea0c39b138.png)
@MelissaSines - we can create a graphic to match what you suggested, but is this what you had in mind?  I think it's too much text for the first page.  I get the desire for more context, but I think there's now too much there.  What do you think?

**Comment by dahnag** [comment]
@readywater - checked in a fix into the uichange branch
