### ISSUE TITLE
Update salary info

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#75]
Update salary info to include:
- [ ] personnel benefits
- [ ] grantmaker-specific roles

**Comment by MelissaSines** [comment]
[Net Grant Salary Data - Positions.docx](https://github.com/Mulligan-Fund/grant-calculator/files/2473093/Net.Grant.Salary.Data.-.Positions.docx)
 Use highlighted salary posistions

**Comment by readywater** [comment]
@dahnag Is this complete with the updated salary info on the DB?

**Comment by dahnag** [comment]
No. TBH, I wasn't sure how to update the salary info in the DB.

**Comment by readywater** [comment]
@dahnag The bootstrapping data lives here:
https://github.com/Mulligan-Fund/grant-calculator-server/blob/master/helpers/bootstrap.js

I can just clear + repopulate it.

**Comment by dahnag** [comment]
Hmmm.  The bootstrap is sequenced correctly, so no changes to make there.
But two are out of sequence in the UI.

**Comment by readywater** [comment]
@dahnag Oh, weird. Can you screenshot the out of sequence? I can try to fix.

**Comment by dahnag** [comment]
![screen shot 2018-12-12 at 5 49 32 pm](https://user-images.githubusercontent.com/32071209/49903826-61f5fc00-fe36-11e8-8ab6-3775950fe72c.jpg)
@readywater - here it is

**Comment by readywater** [comment]
Ahhh, gotcha. So filter into two camps? Okay, will try at a fix.

**Comment by dahnag** [comment]
Maybe? But my main concern is that the last two at the bottom are out of sequence
