### ISSUE TITLE
save button for user info?

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#80]
On https://mulligan-fund.github.io/grant-calculator/profile, there's no clear way to save.  Info entered does not appear to be saved when clicking "return to list"

![image](https://user-images.githubusercontent.com/32071209/50180227-0a90d980-02d7-11e9-9bdc-4095722823d6.png)

**Comment by readywater** [comment]
This should be fixed. The individual input fields save automatically when you click outside of them/tab outside of them. I've implemented a function where we could get a save button just incase though, but will have to wait till later.

**Comment by dahnag** [comment]
This works.  Closing this issue.  We can reassess whether we want/need to add a save button (more for user confidence since saving is happening in progress).
