### ISSUE TITLE
viewing team - no team members appear

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#81]
I have several team members added, but none of them are appearing on https://mulligan-fund.github.io/grant-calculator/people
![image](https://user-images.githubusercontent.com/32071209/50183965-ae7f8280-02e1-11e9-9938-25ee342774b2.png)
(on chrome, fwiw)

**Comment by readywater** [comment]
I kinda fixed this. We'll need to basically wipe and re-bootsrap the database for this to work properly.
