### ISSUE TITLE
Update user guide

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#84]
With new features/functions/data

**Comment by MelissaSines** [comment]
[Net Grant Calculator User Guide.pdf](https://github.com/Mulligan-Fund/grant-calculator/files/3117448/Net.Grant.Calculator.User.Guide.pdf)
@dahnag here is the updated User Guide to upload to the site.

**Comment by dahnag** [comment]
Uploaded updated user guide.
