### ISSUE TITLE
In contributor dropdown, investigate and eliminate "undefined" entries

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#91]
Contributor dropdown has two "undefined" entries.  Investigate source of those entries and delete them; there should be no "undefined" entries on that list.

![image](https://user-images.githubusercontent.com/32071209/52870269-734cd480-3115-11e9-925a-227964a7113a.png)

**Comment by readywater** [comment]
Haven't been able to replicate this bug, unless it's perhaps a user with no name? Anyway, put a few things in here to gut check.
In which case the "undefined" is correct.
