### ISSUE TITLE
Results pages - hide debugging text

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#95]
- [ ] grantseeker results page
![image](https://user-images.githubusercontent.com/32071209/52871572-58c82a80-3118-11e9-9e90-8f87a312976f.png)

- [ ] grantmaker results page
![image](https://user-images.githubusercontent.com/32071209/52871582-5d8cde80-3118-11e9-8a37-5996d1cba76b.png)

Users don't need to see this.

**Comment by readywater** [comment]
b1ca73c
