### ISSUE TITLE
Grant program page - update text

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#98]
The template asks how much are you seeking, it should say What is the grant amount? Or something more generic. * If it’s universal (same on both sides), make generic

And for template wizard:Template Wizard
We have developed several templates for your use as a starting place to calculate how much time it may take a nonprofit to complete your grant process. Use the template wizard below to choose the grant amount, the type of grant, and whether the grant is a new or renewal grant. This will pre-populate the program information pages with nonprofit team members and time spent. Once the wizard populates the grant process steps, you may change this information or alter it if your process does not include one of the steps we’ve outlined. 
You do not have to use the template wizard if you are more familiar with the steps your grantseekers may take to apply for grants and fulfill monitoring and reporting requirements.
Program Information, Details, and Logistics

Fill in the information below about a specific grant program, program details, and program logistics, . We will use this to calculate the final net grant. You may choose whether to save your own work as a template to work from for additional grant programs you may analyze using this tool.

![image](https://user-images.githubusercontent.com/32071209/52971608-199f1100-3386-11e9-8c81-668b67786ed1.png)

**Comment by dahnag** [comment]
@readywater - there are elements of this that seem to be coded in places other than the html.  Happy to dig, but I think you might be in a better position to make these changes.  Text changes need to happen in a couple of places - which will ideally be specific to the user type, or generic enough to address both grantmakers and grantseekers:

- [ ] instructional text for the template wizard
We have developed several templates for your use as a starting place to calculate how much time it may take a nonprofit to complete your grant process. Use the template wizard below to choose the grant amount, the type of grant, and whether the grant is a new or renewal grant. This will pre-populate the program information pages with nonprofit team members and time spent. Once the wizard populates the grant process steps, you may change this information or alter it if your process does not include one of the steps we’ve outlined.
You do not have to use the template wizard if you are more familiar with the steps your grantseekers may take to apply for grants and fulfill monitoring and reporting requirements.
- [ ] text within the template wizard itself
What is the grant amount?  (rather than "how much are you seeking?")
- [ ] instructional text for the program part of the page
Program Information, Details, and Logistics

Fill in the information below about a specific grant program, program details, and program logistics, . We will use this to calculate the final net grant. You may choose whether to save your own work as a template to work from for additional grant programs you may analyze using this tool.

NB - this section should be "Grant" rather than "Program" for grantseekers.

Also happy to make these changes - just want to be sure I'm making changes in the right places.  LMK.

**Comment by readywater** [comment]
@dahnag Updated everything except for the last one. Not 100% sure where it's supposed to go, but you can make the update directly in the YML?
