### ISSUE TITLE
Grantmaker - grantmaker page - update text

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#99]
Update Instructional Text at top:  Now that you’ve entered information for the grantseeker side of the process, you will enter your own grantmaking process details in the form below. Note: The template information from the grantseeker side will show up under Contributors. If you haven’t already added your team members on the Team page, you can go back and do that now.

Update to say: Program Cost to Grantmaker * This needs to updated to reflect that we’ve moved to grantmaker side

**Comment by dahnag** [comment]
@readywater - this is for page 3 of information from the grantmaker perspective (after they've completed the grant program info, and info from the grantee perspective).  We need text to make it clear to them that they're moving into a section that is from their own (grantmaker's) perspective.  Can you point me to where I should make those text changes?

**Comment by readywater** [comment]
I think it would just be page 3 of the yml file. The field name is description.

```
    name: "Program Cost"
    page: 3
    desc: "For each step below, use the drop down menus to add contributors (populated by you in the Staff Contributors section) and the amount of hours spent by each on each task. You may include multiple staff contributors at each level and hours may be estimated to one/tenth of an hour."
```
